import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppThemes {
  static final ThemeData lightTheme = ThemeData(
    // Define Font
    fontFamily: "Axiata",

    primarySwatch: MaterialColor(4279649651, {
      50: Color(0xffeaf2fb),
      100: Color(0xffa9b9ce),
      200: Color(0xff95acce),
      300: Color(0xff849fcd),
      400: Color(0xff759acd),
      500: Color(0xff6995cb),
      600: Color(0xff6496cd),
      700: Color(0xff5c93ce),
      800: Color(0xff568fce),
      900: Color(0xff3F84D0)
    }),
    scaffoldBackgroundColor: Color(0xfffafafa),
    brightness: Brightness.light,

    // Primary Color
    primaryColor: Color(0xff3F84D0),
    primaryColorBrightness: Brightness.dark,
    primaryColorLight: Color(0xffFBFBFB),
    primaryColorDark: Color(0xff2c7ad0),
    primaryTextTheme: TextTheme(
      // display4: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display3: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display2: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display1: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // headline: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // title: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // subhead: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body2: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body1: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      caption: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      // subtitle: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      overline: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    primaryIconTheme: IconThemeData(
      color: Color(0xffffffff),
      opacity: 1,
      size: 24,
    ),

    // Accent Color
    accentColor: Color(0xff4e8cce),
    accentColorBrightness: Brightness.dark,
    accentTextTheme: TextTheme(
      // display4: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display3: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display2: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display1: TextStyle(
      //   color: Color(0xb3ffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // headline: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // title: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // subhead: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body2: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body1: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      caption: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      // subtitle: TextStyle(
      //   color: Color(0xffffffff),
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      overline: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    accentIconTheme: IconThemeData(
      color: Color(0xffffffff),
      opacity: 1,
      size: 24,
    ),

    canvasColor: Color(0xfffafafa),
    cardColor: Color(0xffffffff),
    bottomAppBarColor: Color(0xffffffff),
    dividerColor: Color(0x1f000000),
    highlightColor: Color(0x66bcbcbc),
    splashColor: Color(0x66c8c8c8),
    selectedRowColor: Color(0xfff5f5f5),
    unselectedWidgetColor: Color(0x8a000000),
    disabledColor: Color(0x61000000),
    buttonColor: Color(0xffe0e0e0),
    toggleableActiveColor: Color(0xff307dd2),
    secondaryHeaderColor: Color(0xffeaf2fb),
    textSelectionColor: Color(0xff4c98ee),
    cursorColor: Color(0xff3f84d0),
    textSelectionHandleColor: Color(0xff78b1f1),
    backgroundColor: Color(0xff8dc2fc),
    dialogBackgroundColor: Color(0xffffffff),
    indicatorColor: Color(0xff3f84d0),
    hintColor: Color(0x8a000000),
    errorColor: Color(0xffd32f2f),

    // Define Component Theme
    appBarTheme: AppBarTheme(
        backwardsCompatibility: false,
        brightness: Brightness.dark,
        iconTheme: IconThemeData(color: Colors.black),
        titleTextStyle:
            TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
        backgroundColor: Colors.transparent,
        systemOverlayStyle: SystemUiOverlayStyle(
          statusBarColor: Color(0xff0B3D7C),
        )),
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      // backgroundColor: Color(0xFF04AA59),
      selectedItemColor: Color(0xff3F84D0),
    ),
    buttonTheme: ButtonThemeData(
      textTheme: ButtonTextTheme.normal,
      minWidth: 88,
      height: 36,
      padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: Color(0xff000000),
          width: 0,
          style: BorderStyle.none,
        ),
        borderRadius: BorderRadius.all(Radius.circular(2.0)),
      ),
      alignedDropdown: false,
      buttonColor: Color(0xffe0e0e0),
      disabledColor: Color(0x61000000),
      highlightColor: Color(0x29000000),
      splashColor: Color(0x1f000000),
      focusColor: Color(0x1f000000),
      hoverColor: Color(0x0a000000),
      colorScheme: ColorScheme(
        primary: Color(0xff3F84D0),
        primaryVariant: Color(0xff2775cb),
        secondary: Color(0xff4997ee),
        secondaryVariant: Color(0xff3f81c9),
        surface: Color(0xffffffff),
        background: Color(0xff479bf6),
        error: Color(0xffd32f2f),
        onPrimary: Color(0xffffffff),
        onSecondary: Color(0xffffffff),
        onSurface: Color(0xff000000),
        onBackground: Color(0xffffffff),
        onError: Color(0xffffffff),
        brightness: Brightness.light,
      ),
    ),
    textTheme: TextTheme(
      // display4: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display3: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display2: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // display1: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // headline: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // title: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // subhead: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body2: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      // body1: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      caption: TextStyle(
        color: Colors.black,
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Colors.black,
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      // subtitle: TextStyle(
      //   color: Colors.black,
      //   fontSize: null,
      //   fontWeight: FontWeight.w400,
      //   fontStyle: FontStyle.normal,
      // ),
      overline: TextStyle(
        color: Colors.black,
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      helperStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      hintStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorMaxLines: null,
      // hasFloatingPlaceholder: true,
      isDense: false,
      contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 0, right: 0),
      isCollapsed: false,
      prefixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      suffixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      counterStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      filled: false,
      fillColor: Color(0x00000000),
      errorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedErrorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      disabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      enabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      border: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000),
          width: 1,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
    ),
    iconTheme: IconThemeData(
      color: Color(0xdd000000),
      opacity: 1,
      size: 24,
    ),
    sliderTheme: SliderThemeData(
      activeTrackColor: null,
      inactiveTrackColor: null,
      disabledActiveTrackColor: null,
      disabledInactiveTrackColor: null,
      activeTickMarkColor: null,
      inactiveTickMarkColor: null,
      disabledActiveTickMarkColor: null,
      disabledInactiveTickMarkColor: null,
      thumbColor: null,
      disabledThumbColor: null,
      thumbShape: null,
      overlayColor: null,
      valueIndicatorColor: null,
      valueIndicatorShape: null,
      showValueIndicator: null,
      valueIndicatorTextStyle: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    tabBarTheme: TabBarTheme(
      indicatorSize: TabBarIndicatorSize.tab,
      labelColor: Color(0xffffffff),
      unselectedLabelColor: Color(0xb2ffffff),
    ),
    chipTheme: ChipThemeData(
      backgroundColor: Color(0x1f000000),
      brightness: Brightness.light,
      deleteIconColor: Color(0xde000000),
      disabledColor: Color(0x0c000000),
      labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
      labelStyle: TextStyle(
        color: Color(0xde000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
      secondaryLabelStyle: TextStyle(
        color: Color(0x3d000000),
        fontSize: null,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      secondarySelectedColor: Color(0x3d164573),
      selectedColor: Color(0x3d000000),
      shape: StadiumBorder(
          side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      )),
    ),
    dialogTheme: DialogTheme(
        shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(0.0)),
    )),
  );
}
